# Generated by Django 6.0.3 on 2026-04-03 19:11

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('feedback_type', models.CharField(choices=[('bug', 'System Problem'), ('review', 'Review'), ('suggestion', 'Suggestion'), ('other', 'Other')], max_length=20, verbose_name='feedback type')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'system',
                'verbose_name_plural': 'systems',
                'db_table': 'systems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.models.feedback_file_upload_path, verbose_name='file')),
                ('original_name', models.CharField(max_length=255, verbose_name='original filename')),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes', verbose_name='file size')),
                ('content_type', models.CharField(max_length=100, verbose_name='content type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.feedback', verbose_name='feedback')),
            ],
            options={
                'verbose_name': 'feedback file',
                'verbose_name_plural': 'feedback files',
                'db_table': 'feedback_files',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.system', verbose_name='system'),
        ),
    ]
