# Generated by Django 5.1.4 on 2026-04-06 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Feedback = apps.get_model("api", "Feedback")
    for fb in Feedback.objects.all():
        fb.tracking_id = uuid.uuid4()
        fb.save(update_fields=["tracking_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedback_system_feedbackfile_feedback_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If checked, this feedback will appear on the public status page', verbose_name='show on status page'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='new', max_length=20, verbose_name='status'),
        ),
        # Step 1: Add tracking_id without unique constraint
        migrations.AddField(
            model_name='feedback',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='tracking ID'),
        ),
        # Step 2: Generate unique UUIDs for existing rows
        migrations.RunPython(gen_uuid, migrations.RunPython.noop),
        # Step 3: Make it unique and non-nullable
        migrations.AlterField(
            model_name='feedback',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='tracking ID'),
        ),
        migrations.CreateModel(
            name='FeedbackStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20, verbose_name='status')),
                ('comment', models.TextField(blank=True, default='', verbose_name='operator comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='api.feedback', verbose_name='feedback')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='operator')),
            ],
            options={
                'verbose_name': 'status log',
                'verbose_name_plural': 'status logs',
                'db_table': 'feedback_status_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
