# Generated by Django 5.1.4 on 2026-04-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback_is_public_feedback_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('bug', 'System Problem'), ('review', 'Review'), ('suggestion', 'Suggestion'), ('corruption', 'Corruption Report'), ('other', 'Other')], max_length=20, verbose_name='feedback type'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='phone number'),
        ),
    ]
